on: [push, pull_request]

name: Build (Linux)

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt

  clippy:
    name: Clippy
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        part:
          - rusty-p4
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v2
  
      - name: Checkout pages
        uses: actions/checkout@v2
        with:
          repository: 'another-s347/another-s347.github.io'
          path: 'pages'
          token: ${{secrets.PAT_FOR_PUSH}}
      
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: 'latest'
      
      - name: Build
        run: wasm-pack build --target web --out-name wasm --out-dir ./static

      - name: LS
        run: ls

      - name: Copy
        run: |
          mkdir -p ./pages/static
          cp -r ./static/** ./pages/static

      - name: Push
        run: |
          git config user.name another-s347
          git config user.email s347419313@gmail.com
          git add .
          git commit -m "update index by io-index"
          git push -u https://another-s347:$REPO_KEY@github.com/another-s347/another-s347.github.io.git main
        working-directory: pages
        env:
          REPO_KEY: ${{secrets.PAT_FOR_PUSH}}
      
